// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph2

import (
	"bytes"
	"context"
	"errors"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Comment struct {
		Comment func(childComplexity int, limit *int32, offset *int32) int
		Content func(childComplexity int) int
		ID      func(childComplexity int) int
		UserID  func(childComplexity int) int
	}

	Comment2 struct {
		Comment func(childComplexity int, limit *int32, offset *int32) int
		Content func(childComplexity int) int
		ID      func(childComplexity int) int
		UserID  func(childComplexity int) int
	}

	Post struct {
		Commentable func(childComplexity int) int
		Comments    func(childComplexity int, limit *int32, offset *int32) int
		Content     func(childComplexity int) int
		ID          func(childComplexity int) int
		UserID      func(childComplexity int) int
	}

	Post2 struct {
		Commentable func(childComplexity int) int
		Comments    func(childComplexity int, limit *int32, offset *int32) int
		Content     func(childComplexity int) int
		ID          func(childComplexity int) int
		UserID      func(childComplexity int) int
	}

	Query struct {
	}

	User struct {
		ID      func(childComplexity int) int
		Name    func(childComplexity int) int
		Surname func(childComplexity int) int
	}

	User2 struct {
		ID      func(childComplexity int) int
		Name    func(childComplexity int) int
		Surname func(childComplexity int) int
	}
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "Comment.Comment":
		if e.complexity.Comment.Comment == nil {
			break
		}

		args, err := ec.field_Comment_Comment_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Comment.Comment(childComplexity, args["limit"].(*int32), args["offset"].(*int32)), true

	case "Comment.content":
		if e.complexity.Comment.Content == nil {
			break
		}

		return e.complexity.Comment.Content(childComplexity), true

	case "Comment.id":
		if e.complexity.Comment.ID == nil {
			break
		}

		return e.complexity.Comment.ID(childComplexity), true

	case "Comment.userId":
		if e.complexity.Comment.UserID == nil {
			break
		}

		return e.complexity.Comment.UserID(childComplexity), true

	case "Comment2.Comment":
		if e.complexity.Comment2.Comment == nil {
			break
		}

		args, err := ec.field_Comment2_Comment_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Comment2.Comment(childComplexity, args["limit"].(*int32), args["offset"].(*int32)), true

	case "Comment2.content":
		if e.complexity.Comment2.Content == nil {
			break
		}

		return e.complexity.Comment2.Content(childComplexity), true

	case "Comment2.id":
		if e.complexity.Comment2.ID == nil {
			break
		}

		return e.complexity.Comment2.ID(childComplexity), true

	case "Comment2.userId":
		if e.complexity.Comment2.UserID == nil {
			break
		}

		return e.complexity.Comment2.UserID(childComplexity), true

	case "Post.Commentable":
		if e.complexity.Post.Commentable == nil {
			break
		}

		return e.complexity.Post.Commentable(childComplexity), true

	case "Post.Comments":
		if e.complexity.Post.Comments == nil {
			break
		}

		args, err := ec.field_Post_Comments_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Post.Comments(childComplexity, args["limit"].(*int32), args["offset"].(*int32)), true

	case "Post.content":
		if e.complexity.Post.Content == nil {
			break
		}

		return e.complexity.Post.Content(childComplexity), true

	case "Post.id":
		if e.complexity.Post.ID == nil {
			break
		}

		return e.complexity.Post.ID(childComplexity), true

	case "Post.userId":
		if e.complexity.Post.UserID == nil {
			break
		}

		return e.complexity.Post.UserID(childComplexity), true

	case "Post2.Commentable":
		if e.complexity.Post2.Commentable == nil {
			break
		}

		return e.complexity.Post2.Commentable(childComplexity), true

	case "Post2.Comments":
		if e.complexity.Post2.Comments == nil {
			break
		}

		args, err := ec.field_Post2_Comments_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Post2.Comments(childComplexity, args["limit"].(*int32), args["offset"].(*int32)), true

	case "Post2.content":
		if e.complexity.Post2.Content == nil {
			break
		}

		return e.complexity.Post2.Content(childComplexity), true

	case "Post2.id":
		if e.complexity.Post2.ID == nil {
			break
		}

		return e.complexity.Post2.ID(childComplexity), true

	case "Post2.userId":
		if e.complexity.Post2.UserID == nil {
			break
		}

		return e.complexity.Post2.UserID(childComplexity), true

	case "User.id":
		if e.complexity.User.ID == nil {
			break
		}

		return e.complexity.User.ID(childComplexity), true

	case "User.name":
		if e.complexity.User.Name == nil {
			break
		}

		return e.complexity.User.Name(childComplexity), true

	case "User.surname":
		if e.complexity.User.Surname == nil {
			break
		}

		return e.complexity.User.Surname(childComplexity), true

	case "User2.id":
		if e.complexity.User2.ID == nil {
			break
		}

		return e.complexity.User2.ID(childComplexity), true

	case "User2.name":
		if e.complexity.User2.Name == nil {
			break
		}

		return e.complexity.User2.Name(childComplexity), true

	case "User2.surname":
		if e.complexity.User2.Surname == nil {
			break
		}

		return e.complexity.User2.Surname(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap()
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

var sources = []*ast.Source{
	{Name: "../schema2.graphqls", Input: `# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type User {
  id: ID!
  name: String!
  surname: String!
}

type Post {
  id: ID!
  userId: ID!
  content: String!
  Commentable: Boolean!
  Comments(limit: Int = 10, offset: Int = 0): [Comment!]

}

type Comment {
  id: ID!
  userId: ID!
  content: String!
  Comment(limit: Int = 1, offset: Int = 0): Comment
}`, BuiltIn: false},
	{Name: "../schema3.graphqls", Input: `# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type User2 {
  id: ID!
  name: String!
  surname: String!
}

type Post2 {
  id: ID!
  userId: ID!
  content: String!
  Commentable: Boolean!
  Comments(limit: Int = 10, offset: Int = 0): [Comment!]

}

type Comment2 {
  id: ID!
  userId: ID!
  content: String!
  Comment(limit: Int = 1, offset: Int = 0): Comment
}`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
