package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"qraphQL_posts/api/graph/model"
	"qraphQL_posts/pkg/logger"
	"strconv"

	"go.uber.org/zap"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	new_user := &model.User{
		Name:    input.Name,
		Surname: input.Surname,
		ID:      "",
	}

	_, err := r.userService.Create(ctx, new_user)
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail create user", zap.Error(err))
		return nil, err
	}

	return new_user, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*model.Post, error) {
	comments := []*model.Comment{}
	new_post := &model.Post{
		Commentable: input.Commentable,
		Content:     input.Content,
		ID:          "",
		Comments:    comments,
		UserID:      input.UserID,
	}
	//r.Posts = append(r.Posts, new_post)
	r.postService.Create(r.ctx, new_post)
	return new_post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.NewComment) (*model.Comment, error) {
	//comments := []*model.Comment{}
	new_comment := &model.Comment{
		Content:         input.Content,
		ID:              "",
		Comments:        nil,
		UserID:          input.UserID,
		ParentIDComment: input.ParentIDComment,
	}
	_, err := r.commentService.Create(r.ctx, new_comment)
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail create comment", zap.Error(err))
		return nil, err
	}
	return new_comment, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	idi, err := strconv.Atoi(id)
	fmt.Print("Check this")
	fmt.Print(logger.GetLoggerFromCtx(r.ctx))
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail create user", zap.Error(err))
	}

	if idi < 1 {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail create user becouse ID must be >= 1")
	}
	res, err := r.userService.Get(r.ctx, idi)
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(ctx, "Fail create comment", zap.Error(err))
	}
	return res, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
