package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"qraphQL_posts/api/graph/model"
	"qraphQL_posts/pkg/logger"

	"go.uber.org/zap"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	new_user := &model.User{
		Name:    input.Name,
		Surname: input.Surname,
		ID:      -1,
	}

	res, err := r.userService.Create(ctx, new_user)
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail create user", zap.Error(err))
		return nil, err
	}

	return res, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*model.Post, error) {
	comments := []*model.Comment{}
	new_post := &model.Post{
		Commentable: input.Commentable,
		Content:     input.Content,
		ID:          -1,
		Comments:    comments,
		UserID:      input.UserID,
	}
	//r.Posts = append(r.Posts, new_post)
	res, err := r.postService.Create(r.ctx, new_post)
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail create post", zap.Error(err))
	}
	return res, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.NewComment) (*model.Comment, error) {
	//comments := []*model.Comment{}
	new_comment := &model.Comment{
		Content:         input.Content,
		ID:              -1,
		Comments:        nil,
		UserID:          input.UserID,
		ParentIDComment: input.ParentIDComment,
		PostID:          input.PostID,
	}
	res, err := r.commentService.Create(r.ctx, new_comment)
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail create comment", zap.Error(err))
		return nil, err
	}
	return res, nil
}

// PostUpdate is the resolver for the postUpdate field.
func (r *mutationResolver) PostUpdate(ctx context.Context, input model.UpdatePost) (*model.Post, error) {
	new_post := &model.Post{
		Commentable: input.Commentable,
		ID:          input.ID,
	}
	//r.Posts = append(r.Posts, new_post)
	flag, err := r.postService.Update(r.ctx, new_post)
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail update post", zap.Error(err))
		return nil, err
	}
	if !flag {
		return nil, fmt.Errorf("Error of Update Post")
	}
	return new_post, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: Posts - posts"))
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int32) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: Post - post"))
}

// PostComments is the resolver for the postComments field.
func (r *queryResolver) PostComments(ctx context.Context, postID int32, limit *int32, offset *int32) ([]*model.Comment, error) {
	PostIdi := postID

	res, err := r.commentService.GetAllPost(r.ctx, int(PostIdi))
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail get All comment of the post", zap.Error(err))
		return nil, err
	}
	return res, nil
}

// CommentReplies is the resolver for the commentReplies field.
func (r *queryResolver) CommentReplies(ctx context.Context, commentID int32, limit *int32, offset *int32) ([]*model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentReplies - commentReplies"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int32) (*model.User, error) {
	idi := id

	if idi < 1 {
		logger.GetLoggerFromCtx(r.ctx).Info(r.ctx, "Fail create user becouse ID must be >= 1")
	}
	res, err := r.userService.Get(r.ctx, int(idi))
	if err != nil {
		logger.GetLoggerFromCtx(r.ctx).Info(ctx, "Fail create comment", zap.Error(err))
	}
	return res, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
