# GraphQL schema example
#
# https://gqlgen.com/getting-started/



# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type User {
  id: ID!
  name: String!
  surname: String!
}
input NewUser {
  name: String!
  surname: String!
}

type Post {
  id: ID!
  userId: ID!
  content: String!
  Commentable: Boolean!
  Comments(limit: Int = 10, offset: Int = 0): [Comment]!
}

input NewPost {
  userId: ID!
  content: String!
  Commentable: Boolean!

}

type Comment {
  id: ID!
  userId: ID!
  content: String!
  parentIdComment: ID!
  postId: ID!
  Comments(limit: Int = 1, offset: Int = 0): [Comment]!
}

input NewComment {
  userId: ID!
  parentIdComment: ID!
  content: String!
  postId: ID!
}

type Mutation {
  createUser(input: NewUser!): User!
  createPost(input: NewPost!): Post!
  createComment(input: NewComment!): Comment!
  postUpdate(id: Post!): Post!
}

type Query {
  posts: [Post]
  post(id: ID!): Post
  
  postComments(postId: ID!, limit: Int = 10, offset: Int = 0): [Comment]!
  
  commentReplies(commentId: ID!, limit: Int = 10, offset: Int = 0): [Comment]!
  
  # Получить пользователя
  user(id: ID!): User
  users: [User]!
}
