# GraphQL schema example
#
# https://gqlgen.com/getting-started/



# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type User {
  id: Int!
  name: String!
  surname: String!
}
input NewUser {
  name: String!
  surname: String!
}

type Post {
  id: Int!
  user: User!
  content: String!
  Commentable: Boolean!
  Comments(limit: Int = 10, offset: Int = 0): [Comment]!
}

input NewPost {
  userId: Int!
  content: String!
  Commentable: Boolean!

}

input UpdatePost {
  Id: Int!
  Commentable: Boolean!

}

type Comment {
  id: Int!
  user: User!
  content: String!
  parentIdComment: Int!
  postId: Int!
  Comments(limit: Int = 1, offset: Int = 0): [Comment]!
}

input NewComment {
  userId: Int!
  parentIdComment: Int!
  content: String!
  postId: Int!
}

type Mutation {
  createUser(input: NewUser!): User!
  createPost(input: NewPost!): Post!
  createComment(input: NewComment!): Comment!
  postUpdate(input: UpdatePost!): Post!
}

type Query {
  posts: [Post]
  post(id: Int!): Post
  
  postComments(postId: Int!, limit: Int = 10, offset: Int = 0): [Comment]!
  
  commentReplies(commentId: Int!, limit: Int = 10, offset: Int = 0): [Comment]!
  
  # Получить пользователя
  user(id: Int!): User
  users: [User]!
}
