PORT: 8080
REST_HOST: "0.0.0.0"
TYPE_DB: "PSG" # "IN_MEMORY" for use in memory type of saving and "PSG" for use PostgreSQL

POSTGRES:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT:  5432
  POSTGRES_USER: "forumuser"
  POSTGRES_PASS: "qwerty1234"
  POSTGRES_DB: "forumdb"
  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5


