// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              int32      `json:"id"`
	User            *User      `json:"user"`
	Content         string     `json:"content"`
	ParentIDComment int32      `json:"parentIdComment"`
	PostID          int32      `json:"postId"`
	Comments        []*Comment `json:"Comments"`
}

type Mutation struct {
}

type NewComment struct {
	UserID          int32  `json:"userId"`
	ParentIDComment int32  `json:"parentIdComment"`
	Content         string `json:"content"`
	PostID          int32  `json:"postId"`
}

type NewPost struct {
	UserID      int32  `json:"userId"`
	Content     string `json:"content"`
	Commentable bool   `json:"Commentable"`
}

type NewUser struct {
	Name    string `json:"name"`
	Surname string `json:"surname"`
}

type Post struct {
	ID          int32      `json:"id"`
	User        *User      `json:"user"`
	Content     string     `json:"content"`
	Commentable bool       `json:"Commentable"`
	Comments    []*Comment `json:"Comments"`
}

type Query struct {
}

type UpdatePost struct {
	ID          int32 `json:"Id"`
	Commentable bool  `json:"Commentable"`
}

type User struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}
