// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              string     `json:"id"`
	UserID          string     `json:"userId"`
	Content         string     `json:"content"`
	ParentIDComment string     `json:"parentIdComment"`
	PostID          string     `json:"postId"`
	Comments        []*Comment `json:"Comments"`
}

type Mutation struct {
}

type NewComment struct {
	UserID          string `json:"userId"`
	ParentIDComment string `json:"parentIdComment"`
	Content         string `json:"content"`
	PostID          string `json:"postId"`
}

type NewPost struct {
	UserID      string `json:"userId"`
	Content     string `json:"content"`
	Commentable bool   `json:"Commentable"`
}

type NewUser struct {
	Name    string `json:"name"`
	Surname string `json:"surname"`
}

type Post struct {
	ID          string     `json:"id"`
	UserID      string     `json:"userId"`
	Content     string     `json:"content"`
	Commentable bool       `json:"Commentable"`
	Comments    []*Comment `json:"Comments"`
}

type Query struct {
}

type UpdatePost struct {
	ID          string `json:"Id"`
	Commentable bool   `json:"Commentable"`
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}
