// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID      string   `json:"id"`
	UserID  string   `json:"userId"`
	Content string   `json:"content"`
	Comment *Comment `json:"Comment,omitempty"`
}

type Comment2 struct {
	ID      string   `json:"id"`
	UserID  string   `json:"userId"`
	Content string   `json:"content"`
	Comment *Comment `json:"Comment,omitempty"`
}

type Post struct {
	ID          string     `json:"id"`
	UserID      string     `json:"userId"`
	Content     string     `json:"content"`
	Commentable bool       `json:"Commentable"`
	Comments    []*Comment `json:"Comments,omitempty"`
}

type Post2 struct {
	ID          string     `json:"id"`
	UserID      string     `json:"userId"`
	Content     string     `json:"content"`
	Commentable bool       `json:"Commentable"`
	Comments    []*Comment `json:"Comments,omitempty"`
}

type Query struct {
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}

type User2 struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}
